### ISSUE TITLE
na busca por museus/agentes, substituir o filtro de estados pelo filtro de municípios

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/theme-Museus#5]
![image.png](https://images.zenhubusercontent.com/619668968a927b70ab33ee41/f19132b0-27cc-46e8-9e3b-9258426d62a6)

**Comment by daphnemartinsba** [comment]
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/89fa6128-9f50-441f-8605-1e1baf279b55)
